# help
default:
	just -l

# install poetry
setup:
	pip install --upgrade pip
	pip install poetry

# build docker image
build:
	docker build . -t "backend:$$(poetry version -s)"

# deploy from docker image
deploy:
	docker-compose up -d

# stop backend
stop:
	docker-compose down

